import React, { useEffect, useState } from 'react'
import styles from "./styles.module.css"
const Navbar = () => {
  const [img, setImg] = useState("menu");
  const [menu, setMenu] = useState("-100%");

  function handleMenuToggle() {
    setImg(() => img == "menu" ? "cross" : "menu");
    setMenu(() => menu == "-100%" ? "5px" : "-100%");
  }


  // generated by deepSeek and I hav'nt understood it
  function handleScrolling(sectionIndex) {
    const mainWrapper = document.querySelector('.main-wraper');
    const sectionHeight = window.innerHeight;
    const scrollPosition = sectionIndex * sectionHeight;

    mainWrapper.scrollTo({
      top: scrollPosition,
      behavior: 'smooth'
    });
  }

  useEffect(() => {
    function handleCloseMenu(event) {
      if (menu == "5px" && img == "cross") handleMenuToggle();
    };
    document.addEventListener("mousedown", handleCloseMenu)
  }, [menu, img]);
  return (
    <>
      <nav className={styles.nav}>
        <button
          className={styles.indBtn1}
          onClick={() => handleScrolling(0)}>Saumya Sarma</button>
        <section className={styles.navSection}>
          <button onClick={() => handleScrolling(1)}>Meet Saumya</button>
          <button onClick={() => handleScrolling(2)}>Blogs</button>
          <button onClick={() => handleScrolling(3)}>Heros</button>
        </section>
        <button className={styles.indBtn2}
          onClick={() => handleScrolling(4)}
        >Social Media</button>
        <button
          onClick={handleMenuToggle}
          className={styles.indBtn3}>
          <img src={`/icons/${img}.svg`} />
        </button>
      </nav>
      <div className={styles.menu} style={{ right: `${menu}` }}>
        <button onClick={() => handleScrolling(1)}>Meet Saumya</button>
        <button onClick={() => handleScrolling(2)}>Blogs</button>
        <button onClick={() => handleScrolling(3)}>Heros</button>
        <button onClick={() => handleScrolling(4)}>Social Media</button>
      </div>
    </>
  )
}

export default Navbar
