import React, { useState } from 'react'
import styles from "./styles.module.css"
import Data from './Data.js';
import { data } from 'react-router-dom';
const MeetSaumya = () => {
  const [currentData, setCurrentData] = useState(Data[0]);
  const handleChangeData = (index) => {
    setCurrentData(Data[index]);
  };
  // generated by deepSeek and I hav'nt understood it
  function handleScrolling(sectionIndex, extra) {
    const mainWrapper = document.querySelector('.main-wraper');
    const sectionHeight = window.innerHeight;
    const scrollPosition = sectionIndex * sectionHeight + extra;

    mainWrapper.scrollTo({
      top: scrollPosition,
      behavior: 'smooth'
    });

  }
  return (
    <div className='base-divs'>
      <main className={styles.mainContainer}>
        <section className={styles.image} >
          <img src={`/images/me/${currentData.image}`} />
        </section>

        <section className={styles.textArea}>
          <div className={styles.top}>
            <h1>{currentData.title}</h1>
            <p>
              {currentData.content.split('\n').map((item, index) => (
                <React.Fragment key={index}>
                  {item}
                  <br />
                </React.Fragment>
              ))}
            </p>

          </div>
          <div className={styles.bottom}>
            {Data.map((_, index) => (

              <button
                key={index}
                onClick={() => handleChangeData(index)}
                style={{
                  color: currentData.index == index ? "#000" : "#c4c4c4",
                  transform: currentData.index == index ? "scale(1.5)" : ""
                }}
              >•</button>

            ))}
          </div>
        </section>

      </main>
      <div className={styles.navigateDown}>
        <button className={styles.navigationDown} onClick={() => handleScrolling(2, 200)}>↓</button>
      </div>
    </div >
  )
}

export default MeetSaumya
